services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: analytics
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./backend/.env.example
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/analytics
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  db-data:
